### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by npezolano** [bgamble/pykerberos#1]
I get the following error when I run `pip install pykerebos`. I notice the project hasn't been updated in a while, am I missing anything or is this a valid error?

I am using:

```
python --version
Python 2.7.8 :: Anaconda 2.1.0 (64-bit)
```

```
[root@base admin]# pip install pykerberos
Downloading/unpacking pykerberos
  Downloading pykerberos-1.1.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pykerberos/setup.py) egg_info for package pykerberos
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pykerberos/setup.py", line 44, in <module>
        universal_newlines=True
      File "/tmp/pip_build_root/pykerberos/setup.py", line 31, in check_output
        process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
      File "/usr/local/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/local/anaconda/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pykerberos/setup.py", line 44, in <module>

    universal_newlines=True

  File "/tmp/pip_build_root/pykerberos/setup.py", line 31, in check_output

    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)

  File "/usr/local/anaconda/lib/python2.7/subprocess.py", line 710, in __init__

    errread, errwrite)

  File "/usr/local/anaconda/lib/python2.7/subprocess.py", line 1327, in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pykerberos
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by rossengeorgiev** [comment]
`setup.py` is trying to launch `krb5-config` to get extra compilation flags. With no `krb5-config` on the system, you get that error. Guess I won't be making use of this module.
